export const hostThemeTokens = {
  chartBand: "--sr-chart-band",
  chartFailure: "--sr-chart-failure",
  chartMedian: "--sr-chart-median",
  chartPath: "--sr-chart-path",
  chartRetirement: "--sr-chart-retirement",
  colorAccent: "--sr-color-accent",
  colorAccentSoft: "--sr-color-accent-soft",
  colorBackground: "--sr-color-bg",
  colorBorder: "--sr-color-border",
  colorForeground: "--sr-color-fg",
  colorMuted: "--sr-color-muted",
  colorSurface: "--sr-color-surface",
  fontBody: "--sr-font-body",
  fontMono: "--sr-font-mono",
  motionBase: "--sr-motion-base",
  motionFast: "--sr-motion-fast",
  radiusLarge: "--sr-radius-lg",
  radiusMedium: "--sr-radius-md",
  radiusSmall: "--sr-radius-sm",
  space1: "--sr-space-1",
  space2: "--sr-space-2",
  space3: "--sr-space-3",
  space4: "--sr-space-4",
  space5: "--sr-space-5",
  space6: "--sr-space-6",
  space7: "--sr-space-7",
  space8: "--sr-space-8",
} as const;

export const defaultThemeValues = {
  [hostThemeTokens.chartBand]: "rgba(15, 118, 110, 0.18)",
  [hostThemeTokens.chartFailure]: "#b42318",
  [hostThemeTokens.chartMedian]: "#0f766e",
  [hostThemeTokens.chartPath]: "rgba(31, 26, 23, 0.14)",
  [hostThemeTokens.chartRetirement]: "#b7791f",
  [hostThemeTokens.colorAccent]: "#0f766e",
  [hostThemeTokens.colorAccentSoft]: "#d7efe9",
  [hostThemeTokens.colorBackground]: "#f4efe6",
  [hostThemeTokens.colorBorder]: "rgba(31, 26, 23, 0.12)",
  [hostThemeTokens.colorForeground]: "#1f1a17",
  [hostThemeTokens.colorMuted]: "#5b534d",
  [hostThemeTokens.colorSurface]: "#fffaf4",
  [hostThemeTokens.fontBody]: 'Georgia, "Times New Roman", serif',
  [hostThemeTokens.fontMono]: '"SFMono-Regular", Consolas, "Liberation Mono", monospace',
  [hostThemeTokens.motionBase]: "180ms",
  [hostThemeTokens.motionFast]: "120ms",
  [hostThemeTokens.radiusLarge]: "24px",
  [hostThemeTokens.radiusMedium]: "16px",
  [hostThemeTokens.radiusSmall]: "10px",
  [hostThemeTokens.space1]: "4px",
  [hostThemeTokens.space2]: "8px",
  [hostThemeTokens.space3]: "12px",
  [hostThemeTokens.space4]: "16px",
  [hostThemeTokens.space5]: "24px",
  [hostThemeTokens.space6]: "32px",
  [hostThemeTokens.space7]: "48px",
  [hostThemeTokens.space8]: "64px",
} as const;

export type HostThemeTokenName = (typeof hostThemeTokens)[keyof typeof hostThemeTokens];
